include_recipe 'dev-machine::apt'
include_recipe 'dev-machine::packages'
include_recipe 'dev-machine::ruby'
include_recipe 'dev-machine::node'
include_recipe 'dev-machine::golang'
include_recipe 'dev-machine::python'
