include_recipe "dev-machine::apt"
include_recipe "dev-machine::packages"
include_recipe "dev-machine::ruby-193"
include_recipe "dev-machine::python"
include_recipe "dev-machine::dotfiles"
include_recipe "dev-machine::golang"
include_recipe "dev-machine::go-tools"
include_recipe "dev-machine::node"
