include_recipe "dev-machine::apt"
include_recipe "dev-machine::packages"
include_recipe "dev-machine::ruby"
include_recipe "dev-machine::dotfiles"
include_recipe "dev-machine::dotvim"
include_recipe "dev-machine::git-surf"
