# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box =  'box-cutter/ubuntu1404-desktop'
  config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.memory = 8 * 1024
    vb.cpus = 3
  end

  config.vm.define 'default' do |default|
    default.vm.hostname = 'debox'
    default.vm.network 'private_network', ip: '192.168.34.10'
    default.vm.provision 'shell',
                         name: 'bootstrap',
                         keep_color: true,
                         path: '../bootstrap.sh'

    default.vm.provision 'shell',
                         name: 'storage',
                         keep_color: true,
                         path: '../storage-bootstrap.sh'
  end
end
