#!/usr/bin/env bash

echo "ES"
vagrant ssh storage -c 'sudo service elasticsearch status'
vagrant ssh storage -c 'sudo service elasticsearch start'

echo "Redis"
vagrant ssh storage -c 'sudo service redis-server status'
vagrant ssh storage -c 'sudo service redis-server start'

echo "rabbitmq"
vagrant ssh storage -c 'sudo service rabbitmq-server status | head -4'
vagrant ssh storage -c 'sudo service rabbitmq-server start'
